### PR TITLE
Add heats-of-reaction directory that contains the jupyter notebook & supporting files

### PR DESCRIPTION
**Pull request by megcrow**
Add heats-of-reaction directory that contains the jupyter notebook used to calculate heats of reaction and required input files, heats-25C.csv which is produced by running the jupyter notebook, and nasa-polynomial-doc.pdf which details calculations using nasa polynomial coefficients.

### CODE REVIEW

**Comment by wigging** [comment]
Looks like you included the checkpoints file which typically isn't put into version control. Please remove it from the pull request.

**Comment by wigging** [comment]
Also, make sure you have a `.gitignore` file on your computer. You can set it up globally on your computer so it works with all your repositories. See [here](https://stackoverflow.com/questions/27850222/what-is-gitignore-exactly) for more info about the ignore file. And this [site](https://gitignore.io) is handy for creating such files.

**Comment by megcrow** [comment]
Thanks Gavin! That site is great, I will be using that for my future projects now. I added the .gitignore and removed the .ipynb_checkpoints file. Let me know if there's anything else you'd like me to fix!

**Comment by wigging** [comment]
@megcrow I merged everything into the master branch. Notice that I moved the gitignore file into the root directory so it will apply to the whole repository. I also added some items to the ignore file. You can pull down the latest changes to your master branch and you'll be good to go. Thank you for the contribution. 👍

**Pull request merged**
